#!/bin/sh

MONGO_URL="${DOTCLOUD_DB_MONGODB_LOGIN}:${DOTCLOUD_DB_MONGODB_PASSWORD}@${DOTCLOUD_DB_MONGODB_HOST}:${DOTCLOUD_DB_MONGODB_PORT}"

exec ./wiki.exe \
         --logs-path /var/log/supervisor \
         --db-remote "$MONGO_URL" \
         --verbose 8 \
         $@
